config/routes.rb
Merchant::Application.routes.draw do

  get "dashboard/index"
  resources :orders

  resources :categories

  resources :order_items, only: [:create, :destroy]
  resources :carts, only: [:show, :destroy]

  resources :products do 
    resources :images
  end

  root 'products#index'
  resources :mails, only: [:index, :create] do
    collection do 
      delete 'destroy_multiple'
    end
  end
  get '/mails/sent' => 'mails#sent'

  resources :users,     only: [:new, :create, :edit, :update]
  resources :sessions,  only: [:new, :create, :destroy]
  resources :avatars,   only: [:edit,:update, :destroy]
  resources :password_resets

  get 'signup', to: "users#new",        as: 'signup'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout' 
  
  namespace :admin do 
    get '', to: 'dashboard#index', as: '/' 
    resources :products, only: [ :index ]
    resources :users, only: [ :index ]
  end

end

app/views/shared/_content_header.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Dashboard
        <small>Control panel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
    </ol>
</section>

app/views/shared/_header.html.erb
<header class="header">
    <%= link_to "Electro & Computers", root_url, class: 'logo' %>
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="navbar-left">
            <ul class="nav navbar-nav">
                <li><%= link_to "Products", products_path %></li>
            </ul>
        </div>
        <div class="navbar-right">
            <ul class="nav navbar-nav">
                <!-- Sales -->
                <li class="dropdown sales-menu">
                    <%= render @cart %>
                </li>
             <% if current_user %>
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="glyphicon glyphicon-user"></i>
                        <span><%= current_user.full_name %> <i class="caret"></i></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header bg-light-blue">
                            <%= image_tag(current_user.profile.avatar.url, :class => "img-circle", :alt => "User Image" ) %>
                            <p>
                                <%= current_user.full_name %>
                                <small> Member since:  <%= current_user.created_at.strftime('%B %e') %> </small> 
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <%= link_to "Profile", edit_user_path(current_user), class: "btn btn-default btn-flat" %>
                            </div>
                            <div class="pull-right">
                                <%= link_to "Log out", logout_path, class: "btn btn-default btn-flat" %>
                            </div>
                        </li>
                    <% else %> 
                        <li> <%= link_to "Log in",  login_path,  class: "btn btn-sm btn-flat" %>  </li>
                        <li> <%= link_to "Sign Up", signup_path, class: "btn btn-sm btn-flat" %>  </li>
                     <% end %> 
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

app/views/shared/_notifications.html.erb
<% [:error, :alert, :success, :info].each do |type| %>
  <% unless flash[type].blank? %>
    <div class="alert alert-<%= type %> alert-dismissable">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <p><%= flash[type] %></p>
    </div>
  <% end %>
<% end %>

app/views/shared/_sidebar.html.erb
<aside class="left-side sidebar-offcanvas">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <% if current_user %>
            <div class="pull-left image">
                <%= image_tag(current_user.profile.avatar.url, :class => "img-circle", :alt => "User Image" ) %>
            </div>
            <div class="pull-left info">
                <p>Hello, <%= current_user.user_name %> </p>

                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        <% else %> 
            <div class="col-xs-6 text-center">
               <!-- TO-DO  -->
               <%= link_to "Log in",  login_path,  class: "btn btn-sm bg-purple" %>
             </div>
            <div class="col-xs-6 text-center">
                <!-- TO-DO  -->
                <%= link_to "Sign Up", signup_path, class: "btn btn-sm bg-purple" %>
            </div>
        <% end %> 
        </div>
         <!-- search form -->
        <%= form_tag products_path, :method => :get, class: "sidebar-form" do %>
        <div class="input-group">
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search..." %>
             <span class="input-group-btn">
            <%= link_to_submit class:"btn btn-flat", id: "search-btn" do %>
                <i class="fa fa-search"></i>
            <% end %>
            </span>
        </div>
        <% end %>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li>
                <%= link_to(root_path) do %>
                    <i class="fa fa-dashboard"></i> <span>Main</span>
                <% end %>
            </li>
            <% if current_user %>
            <li>
                <%= link_to(orders_path) do %>
                    <i class="fa fa-list-alt"></i> <span>Orders</span> <small class="badge pull-right bg-green">new</small>
                <% end %>
            </li>
            <% end %>
            <% if can? :manage, :all %>
            <li>
                <%= link_to(categories_path) do %>
                    <i class="fa fa-unsorted"></i> <span>Categories</span>
                <% end %>
            </li>
            <li>
                <%= link_to(mails_path) do %>
                    <i class="fa fa-envelope"></i> <span>Mailbox</span>
                    <small class="badge pull-right bg-yellow"><%= AdminMail.received.count %></small>
                <% end %>
            </li>
            <li>
                <%= link_to(admin_path) do %>
                    <i class="fa fa-user"></i> <span>Admin Dashboard</span>
                <% end %>
            </li>
            <li>
                <%= link_to(admin_users_path) do %>
                    <i class="fa fa-users"></i> <span>Admin Users</span>
                <% end %>
            </li>
            <li>
                <%= link_to(admin_products_path) do %>
                    <i class="fa fa-tasks"></i> <span>Admin Products</span>
                <% end %>
            </li>
            <% end %>

            <% Category.roots.each do |root| %>
                <%= render 'categories/submenu_categories', categories: root.subtree.arrange %>
            <% end %>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

app/views/shared/_stat_boxes.html.erb
<!-- Small boxes (Stat box) -->
<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>
                    150
                </h3>
                <p>
                    New Orders
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3>
                    53<sup style="font-size: 20px">%</sup>
                </h3>
                <p>
                    Bounce Rate
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>
                    44
                </h3>
                <p>
                    User Registrations
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3>
                    65
                </h3>
                <p>
                    Unique Visitors
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-pie-graph"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div><!-- ./col -->
</div><!-- /.row -->