config/routes.rb
Merchant::Application.routes.draw do

  get "dashboard/index"
  resources :orders

  resources :categories

  resources :order_items, only: [:create, :destroy]
  resources :carts, only: [:show, :destroy]

  resources :products do 
    resources :images
  end

  root 'products#index'
  resources :mails, only: [:index, :create] do
    collection do 
      delete 'destroy_multiple'
    end
  end
  get '/mails/sent' => 'mails#sent'

  resources :users,     only: [:new, :create, :edit, :update]
  resources :sessions,  only: [:new, :create, :destroy]
  resources :avatars,   only: [:edit,:update, :destroy]
  resources :password_resets

  get 'signup', to: "users#new",        as: 'signup'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout' 
  
  namespace :admin do 
    get '', to: 'dashboard#index', as: '/' 
    resources :products, only: [ :index ]
    resources :users, only: [ :index ]
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  belongs_to :user
  
  def add_product(product_id)
    current_item = order_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = order_items.build(product_id: product_id)
    end
    current_item
  end
  
  def total_price
    order_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :destroy]

  def show
  end

  def destroy
    @cart.destroy
    session[:cart_id] = nil
    redirect_to products_path
    flash[:success] = 'Your cart is currently empty.'
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params[:cart]
    end
end

app/views/carts/_cart.html.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-shopping-cart"></i>
    <span class="label label-success"><%= @cart.order_items.size %></span>
</a>
<ul class="dropdown-menu">
    <li class="header">You have <%= cart.order_items.size%> items in your cart</li>
    <li>
        <!-- inner menu: contains the actual data -->
        <ul class="menu">
          <% cart.order_items.each do |item| %>
            <li><!-- start message -->
                <%= link_to product_path(item.product) do %>
                    <div class="pull-left">
                      <% if item.product.images.any? %>
                       <%= image_tag item.product.images.first.photo.url(:thumb), alt: "User Image" %>
                      <% else %>
                        <%= image_tag "missing.png", :size => '50', alt: "User Image" %>
                      <% end %>
                    </div>
                    <h4>
                       <span class="label label-warning"><%= item.quantity %></span> <%= item.product.title %>
                        <small><i class="fa fa-clock-o"></i> <%= time_ago_in_words(item.created_at) %> </small>
                    </h4>
                    <p><%= truncate(item.product.description, length: 50) %></p>
                <% end %>
            </li><!-- end message -->
          <% end %>
        </ul>
    </li>
    <li class="footer"><%= link_to "See all items", cart_path(cart) %></li>
</ul>

app/views/carts/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <i class="fa fa-shopping-cart"></i>
        <h3 class="box-title">Your cart</h3>
      </div><!-- /.box-header -->
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <tbody><tr>
            <th>Quantity</th>
            <th>Image</th>
            <th>Title</th>
            <th>Description</th>
            <th>Price</th>
            <th>Controls</th>
          </tr>
          <% @cart.order_items.each do |item| %>
          <tr>
            <td><%= item.quantity %></td>
            <% if item.product.images.any? %>
              <td><%= image_tag item.product.images.first.photo.url(:thumb) %></td>
            <% else %>
              <td><%= image_tag "missing.png", :size => '110' %></td>
            <% end %>
            <td><%= item.product.title %></td>
            <td><%= truncate(item.product.description, length: 105) %></td>
            <td><%= number_to_currency(item.total_price) %></td>
            <td><%= link_to "Delete", item, class: "btn btn-danger btn-sm destroy_item_#{item.id}", confirm: "Are you sure? ", method: 'delete', remote: true %></td>
          </tr>
          <% end %>
          <tr class="total_line">
            <td colspan="5">Total</td>
            <td><h4><span class="label label-success"> <%= number_to_currency(@cart.total_price) %></span></h4></td>
          </tr>
        </tbody></table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div>
</div>
  <div class="col-xs-12">

<% if current_user %>
  <%= button_to 'Checkout', new_order_path, class: 'btn btn-success',  method: :get, data: { confirm: 'Are you sure?' } %>
  <%= button_to 'Empty cart', @cart, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

</div>