config/routes.rb
Merchant::Application.routes.draw do

  get "dashboard/index"
  resources :orders

  resources :categories

  resources :order_items, only: [:create, :destroy]
  resources :carts, only: [:show, :destroy]

  resources :products do 
    resources :images
  end

  root 'products#index'
  resources :mails, only: [:index, :create] do
    collection do 
      delete 'destroy_multiple'
    end
  end
  get '/mails/sent' => 'mails#sent'

  resources :users,     only: [:new, :create, :edit, :update]
  resources :sessions,  only: [:new, :create, :destroy]
  resources :avatars,   only: [:edit,:update, :destroy]
  resources :password_resets

  get 'signup', to: "users#new",        as: 'signup'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout' 
  
  namespace :admin do 
    get '', to: 'dashboard#index', as: '/' 
    resources :products, only: [ :index ]
    resources :users, only: [ :index ]
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true

  has_many :order_items
  before_destroy :ensure_not_referenced_by_any_order_item

  has_many :categorizations
  has_many :categories, through: :categorizations
  
  private

  searchable do
     text :title, :description
  end

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_order_item
    if order_items.empty?
      return true
    else
      errors.add(:base, "Order Items present. You can't delete this item")
      return false
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  authorize_resource :class => false

  def index
    @products = Product.all
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  authorize_resource only: [:new, :edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @search = Product.search do 
      fulltext params[:search]
    end
    @products = @search.results
    # @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
    @product.images.build
    #5.times { @product.images.build }
  end

  def edit
    @product.images.build
    #5.times { @product.images.build }
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = 'Product was successfully created.'
      redirect_to @product
    else
      flash[:error] = "Product wasn't created."
      render :new 
    end
  end

  def update
    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to @product  }
        format.json { head :update }
      else
        render :edit
      end
    end
  end

  def destroy
    if @product.destroy 
      flash[:success] = "The products was successfully deleted"
    else
      flash[:error] = @product.errors[:base].first
    end
    redirect_to products_url
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :price, :category_ids => [], images_attributes: [ :id, :photo ])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<% if @product.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <i class="fa fa-ban"></i>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      <% @product.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
  </div>
<% end %>

<%= form_for @product, :html => { :multipart => true } do |f| %>
<div class="row">
<div class="col-md-6 col-md-offset-1">
  <div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Product info.</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
      <div class="box-body">
          <div class="form-group">
              <%= f.label :title %>
              <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
          </div>
          <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, class:"form-control",  placeholder:"Description" %>
          </div>
          <div class="form-group">
              <%= f.collection_select :category_ids, Category.leaves, :id, :name, {}, {multiple: true, class: "form-control"} %>
          </div>
          <div class="form-group">
              <%= f.label :price %>
              <%= f.text_field :price, class:"form-control",  placeholder:"500.00" %>
          </div>
      </div> <!-- /.box-body -->
    <div class="box-footer">
        <%= f.submit class: "btn bg-black btn-block"%>
    </div>
  </div> <!-- /.box -->
</div>

<div class="col-md-4">
  <div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Add image</h3>
    </div><!-- /.box-header -->
    <div class="box-body text-center">
          <div class="thumbnail">
            <div class="form-group">
              <%= f.fields_for :images do |image| %>
                <% if image.object.new_record? %>
                   <%= image.file_field :photo, multiple: true, name: "product[images_attributes][#{@product.images.size}][photo]" %>
                <% end %>
              <% end %>
          </div>
          </div>
    </div><!-- /.box-body -->
    <div class="box-footer">
    </div>
  </div>
</div>
</div>
<% end %>

<% # jquery upload template # %>
<script id="template-upload" type="text/x-tmpl"><div class="upload">{%=o.name%}<div class="progress"><div class="bar" style="width: 0%"></div></div></div></script>

<div class="row">
<div class="col-md-10 col-md-offset-1 imgs">
  <% if @product.images.any? %>
    <% @product.images.each do |image| %>
     <% unless image.new_record? %>
        <%= render 'upload_image', :product => @product, :image => image %>    
      <% end %>
    <% end %>
  <% else %>
    <div class="col-md-8 col-md-offset-2">
    <div class="box box-primary">
      <div class="box-header">
          <h3 class="box-title"></h3>
      </div><!-- /.box-header -->
       <div class="box-body">
        <div class="callout callout-danger">
          <h4>There are no images yet.</h4>
          <p>Return back to the edit page to add a new one.</p>
      </div>
       </div>  <!-- /.box-body -->
      </div> <!-- /.box -->
    </div> <!-- /.col-md-8 -->
  <% end %>
</div>
</div>

app/views/products/_product.html.erb
<div class="col-md-2">
  <%= link_to product do %>
  <div class="box box-solid">
      <div class="box-header">
          <i class="fa fa-tag"></i>
          <h3 class="product-box-title"><%= truncate(product.title, length: 16) %></h3>
      </div><!-- /.box-header -->
      <div class="box-body clearfix">
        <div class="col-md-12 text-center">
            <% if product.images.any? %>
              <%= image_tag product.images.first.photo.url(:thumb) %> 
            <% else %>
              <%= image_tag "missing.png", :size => '100' %>
            <% end %>
        </div>
      </div><!-- /.box-body -->
    <% end %>
      <div class="box-footer clearfix">
        <div class="col-xs-7">
          <%= button_to "Add to cart", order_items_path(product_id: product), remote: true, class: 'btn btn-warning btn-sm' %>
        </div>
        <div class="col-xs-5">
          <small>Price</small>
          <b class="text-green"> <%= product.price %> </b>
        </div>
      </div><!-- /.box-body -->
  </div><!-- /.box -->
</div>

app/views/products/_upload_image.html.erb
<div class="col-md-4 text-center">
  <div class="box box-solid">
      <div class="box-header">
          <i class="fa fa-camera"></i>
          <h3 class="box-title"></h3>
      </div><!-- /.box-header -->
      <div class="box-body ">
        <%= image_tag image.photo.url(:small) %> 
      </div><!-- /.box-body -->
      <div class="box-footer clearfix">
        <%= link_to 'Destroy', [product, image], class: "btn btn-sm btn-danger", confirm: 'Are you sure?', method: :delete %>
      </div><!-- /.box-body -->
  </div><!-- /.box -->
</div> <!-- /.col-md-4-->

app/views/products/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @product, class: 'btn btn-warning' %> 
<%= link_to 'Back', products_path, class: 'btn btn-primary' %>

app/views/products/index.html.erb
<div class="col-md-12">
  <% if @products.present? %>
    <%= render @products %>
  <% else %>
    <div class="box box-solid">
      <div class="box-header">
         <i class="fa fa-exclamation-circle"></i>
         <h3 class="box-title">Products</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <div class="callout callout-info">
            <h4> No products</h4>
            <p>Sorry! There are no products at the moment. You need to add one. </p>
          </div>
         </div><!-- /.box-body -->
        </div><!-- /.box -->
  <% end %> 
</div>

<% if can? :manage, Product.new %>
  <%= link_to 'Add new products', new_product_path, class: 'btn btn-primary' %>
<% end %>

app/views/products/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', products_path, class: 'btn btn-primary' %>

app/views/products/show.html.erb
<div class="col-md-6 col-md-offset-1">
  <div class="box box-danger">
    <div class="box-header">
        <h3 class="box-title"><%= @product.title %></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
       <%= @product.description %>
       <hr>
        <% @product.categories.each do |category| %>
            <span class="label label-success"> <%= category.name %> </span> &nbsp;
        <% end %>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
       <div class="col-xs-8">
        <%= button_to "Add to cart", order_items_path(product_id: @product), remote: true, class: 'btn btn-warning btn-sm' %>

          <% if can? :manage, @product %>
            <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-warning btn-sm' %> 
            <%= link_to "Delete", @product, class: 'btn btn-danger btn-sm', confirm: "Are you sure? ", method: 'delete' %>
            <%= link_to 'Back', products_path, class: 'btn btn-primary btn-sm' %>
          <% end %>
        </div>
        <div class="col-xs-4">
          <h4> Price <%= @product.price %> </h4>
        </div>
    </div> <!-- /.box-footer -->
  </div>
</div>

<div class="col-md-4">
  <div class="box box-danger">
    <div class="box-header">
        <h3 class="box-title">Product images</h3>
    </div><!-- /.box-header -->
    <div class="box-body text-center">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <% if @product.images.any? %>
                <% @product.images.each_with_index do |image,index| %>
                    <li data-target="#carousel-example-generic" data-slide-to="<%= index %>"<%= " class=active" if index==0 %>></li> 
                <% end %>
            <% else %>
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <% end %>
        </ol>
        <div class="carousel-inner text-center">
            <% if @product.images.any? %>
                <% @product.images.each_with_index do |image,index| %>
                    <div class="item text-center <%= "active" if index==0 %>">
                        <%= image_tag image.photo.url(:small) %> 
                        <div class="carousel-caption"></div>
                    </div>
                <% end %>
            <% else %>
                <div class="item active">
                    <%= image_tag "missing.png", :size => '150' %>
                    <div class="carousel-caption">Missing image</div>
                </div>
            <% end %>
        </div>
         <% if @product.images.size > 1 %>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left black-glypth"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right black-glypth"></span>
            </a>
         <% end %>
    </div>
    </div><!-- /.box-body -->
  </div>
</div>

app/views/products/update.js.erb
<% if @product.new_record? or @product.errors.any? %>
  alert('Something is wrong with the image. Choose another one.');
<% else %>
  $('.imgs').append("<%=j render 'upload_image', :product => @product, :image => @product.images.last  %>");
<% end %>